### ISSUE TITLE
Bundler could not find compatible versions for gem "jekyll":

### ISSUE THREAD

**Issue by sebastiancretu** [Crunch09/jeql#11]
When I try to run bundler install i receive the following error:

Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.2.0) x86_64-darwin-19

    jeql x86_64-darwin-19 was resolved to 0.2.1, which depends on
      jekyll (~> 3.7) x86_64-darwin-19

The only way to bypass this is to downgrade jekyll. Can it be also compatible with the new version of jekyll maybe ?

Thanks

**Comment by Crunch09** [comment]
Thanks @sebastiancretu for raising. I'll add support for newer jekyll versions within the next week or so

**Comment by Crunch09** [comment]
I pushed a [new release (version 0.3)](https://rubygems.org/gems/jeql/versions/0.3) which should allow you to use newer Jekyll versions. Please let me know if you still encounter any issues and thanks again for your report!
