### ISSUE TITLE
Directory for query files in documentation differs from the one used in code

### ISSUE THREAD

**Issue by GBognar** [Crunch09/jeql#6]
The ['*GraphQL queries*' section](https://github.com/Crunch09/jeql/blob/master/README.md#graphql-queries)  of the `README.md` states that the GraphQL 
queries are in the `_jeql` directory:

> Queries in jeql are specified as json files and live within the _jeql directory of your jekyll site.
> An example query file would have the following content:

But according to the actual code (in [line 7 of `lib/jqel/query.rb`](https://github.com/Crunch09/jeql/blob/master/lib/jeql/query.rb#L7)), the directory is `_graphql`:

```ruby
   @query_file = File.read File.expand_path "./_graphql/#{query_name}.json", source_dir
```

**Comment by Crunch09** [comment]
Thanks @GBognar , good spot! I'll fix this.
